<style></style>
<template>
    <div></div>
</template>
<script>
    export default {
        props:{
            prop:{
                type:String,
                default:""
            },
            label:{
                type:String,
                default:""
            },
            width:{
                type:String,
                default:"100px"
            },
            align:{
                type:String,
                default:"center"
            },
            fixed:{
                type:String,
                default:""
            },
            formatter:{
                type:Function,
                default:null
            },
            checkbox:{
                type:Boolean,
                default:false
            },
            filterCheckbox:{
                type:Function,
                default:null
            }
        },
        created:function(){
            if(this.$parent && this.$parent.$vnode && this.$parent.$vnode.tag && /^vue-component-\d*-mj-table$/.test(this.$parent.$vnode.tag)){
                if(this.checkbox){
                    if(!this.$parent.checkboxFlag){
                        this.$parent.columnList.push({
                            prop:this.prop,
                            label:this.label,
                            width:"60px",
                            align:this.align,
                            fixed:this.fixed,
                            formatter:this.formatter,
                            checkbox:this.checkbox
                        });
                        this.$parent.filterCheckbox = this.filterCheckbox || function(){return false;};
                        this.$parent.checkboxFlag = true;
                    }
                }else{ 
                    this.$parent.columnList.push({
                        prop:this.prop,
                        label:this.label,
                        width:this.width,
                        align:this.align,
                        fixed:this.fixed,
                        formatter:this.formatter,
                        checkbox:this.checkbox
                    });
                }
            }
        },
        name:"mj-table-column"
    }
</script>